default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  strict: false
  host: localhost
  username: root

development:
  <<: *default
  database: rortutorail4_2_dev

test:
  <<: *default
  database: rortutorail4_2_test

production:
  <<: *default
  database: rortutorail4_2_pd
